export const actionTypes = {
    GET_PUBLIC_ACCESS_TOKEN: 'GET_PUBLIC_ACCESS_TOKEN',
    SET_PUBLIC_ACCESS_TOKEN: 'SET_PUBLIC_ACCESS_TOKEN',
    LOG_USER_IN: 'LOG_USER_IN',
    SET_PRIVATE_ACCESS_TOKEN: 'SET_PRIVATE_ACCESS_TOKEN',
    REGISTER_USER: 'REGISTER_USER'
};
